### ISSUE TITLE
NCMBException

### ISSUE THREAD

**Issue by ikemura23** [banbara23/Yaeyama-Liner-Checker#144]
# 11NCMBConnection.java line 168

com.nifty.cloud.mb.core.NCMBConnection.sendRequest

``` java
NCMBException: Unable to resolve host "mb.api.cloud.nifty.com": No address associated with hostname
       at com.nifty.cloud.mb.core.NCMBConnection.sendRequest(NCMBConnection.java:168)
       at com.nifty.cloud.mb.core.NCMBService.sendRequest(NCMBService.java:181)
       at com.nifty.cloud.mb.core.NCMBObjectService.searchObject(NCMBObjectService.java:336)
       at com.nifty.cloud.mb.core.NCMBQuery.find(NCMBQuery.java:64)
       at com.ikmr.banbara23.yaeyama_liner_checker.api.StatusListApi$2.call(StatusListApi.java:52)
       at com.ikmr.banbara23.yaeyama_liner_checker.api.StatusListApi$2.call(StatusListApi.java:32)
       at rx.Observable$2.call(Observable.java:233)
       at rx.Observable$2.call(Observable.java:225)
       at rx.Observable$2.call(Observable.java:233)
       at rx.Observable$2.call(Observable.java:225)
       at rx.Observable.unsafeSubscribe(Observable.java:8741)
       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by ikemura23** [comment]
[NIFTYCloud-mbaas/ncmb_android](https://github.com/NIFTYCloud-mbaas/ncmb_android)
