### ISSUE TITLE
トップ画面で天気吹き出しタップでアプリが落ちる

### ISSUE THREAD

**Issue by ikemura23** [banbara23/Yaeyama-Liner-Checker#166]
100%落ちる

**Comment by ikemura23** [comment]
Crashlytics
```
# Crashlytics - plaintext stacktrace downloaded by banbara at Thu, 22 Dec 2016 07:17:49 GMT
# URL: https://fabric.io/banbara23/android/apps/com.banbara.yaeyama.liner.checker/issues/585b79e30aeb16625b4a7305/sessions/585B7A0B03180001020D785F2378120E_04b2a7f2233247ac9ae525714fed0f56_0_v1
# Organization: banbara23
# Platform: android
# Application: やいまふに
# Version: 2.7.0 (25)
# Bundle Identifier: com.banbara.yaeyama.liner.checker
# Issue #: 27
# Issue ID: 585b79e30aeb16625b4a7305
# Session ID: 585B7A0B03180001020D785F2378120E_04b2a7f2233247ac9ae525714fed0f56_0_v1
# Date: 2016-12-22T07:00:28Z
# OS Version: 7.0
# Device: Nexus 6
# RAM Free: 44.8%
# Disk Free: 40%

#0. Crashed: main: 0 0 0x0000000000000000
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity.setCompanyStatusView(TopActivity.java:116)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity.changeCompanyStatus(TopActivity.java:110)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity.access$000(TopActivity.java:48)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity$1.onNext(TopActivity.java:102)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity$1.onNext(TopActivity.java:89)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
       at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

--

Non-fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ikmr.banbara23.yaeyama_liner_checker.entity.Status.ordinal()' on a null object reference
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity.setCompanyStatusView(TopActivity.java:116)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity.changeCompanyStatus(TopActivity.java:110)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity.access$000(TopActivity.java:48)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity$1.onNext(TopActivity.java:102)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity$1.onNext(TopActivity.java:89)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
       at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

#0. Crashed: main: 0 0 0x0000000000000000
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity.setCompanyStatusView(TopActivity.java:116)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity.changeCompanyStatus(TopActivity.java:110)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity.access$000(TopActivity.java:48)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity$1.onNext(TopActivity.java:102)
       at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity$1.onNext(TopActivity.java:89)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
       at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by ikemura23** [comment]
Android Studioのエラーログ
```
java.lang.NullPointerException: uriString
    at android.net.Uri$StringUri.<init>(Uri.java:467)
    at android.net.Uri$StringUri.<init>(Uri.java:457)
    at android.net.Uri.parse(Uri.java:429)
    at com.ikmr.banbara23.yaeyama_liner_checker.util.CustomTabUtil.start(CustomTabUtil.java:14)
    at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity.bubbleClick(TopActivity.java:233)
    at com.ikmr.banbara23.yaeyama_liner_checker.activity.TopActivity$$ViewBinder$2.doClick(TopActivity$$ViewBinder.java:34)
    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
    at android.view.View.performClick(View.java:4438)
    at android.view.View$PerformClick.run(View.java:18422)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5001)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)
```
